### ISSUE TITLE
Warning: grunt.util._(...).chain(...).pluck is not a function Use --force to continue.

### ISSUE THREAD

**Issue by konstantinj** [gruntjs/grunt-contrib-clean#90]
with grunt 1.0.1 and grunt-contrib-clean 1.0.0.

**Comment by hilnius** [comment]
I have the same error

**Comment by chocolateboy** [comment]
**Packages**:

 * grunt v0.4.5
 * grunt-cli v1.2.0
 * grunt-contrib-clean v0.6.0
 * grunt-legacy-util 0.2.0
 * node v6.3.1
 * npm 3.10.5

**Error**:

    TypeError: grunt.util._(...).chain(...).pluck is not a function
        at Object.<anonymous> (node_modules/grunt/lib/grunt/task.js:260:55)
        at Object.<anonymous> (node_modules/grunt-contrib-clean/tasks/clean.js:53:9)
        at Object.<anonymous> (node_modules/grunt/lib/grunt/task.js:265:15)
        at Object.thisTask.fn (node_modules/grunt/lib/grunt/task.js:82:16)
        at Object.<anonymous> (node_modules/grunt/lib/util/task.js:301:30)
        at Task.runTaskFn (node_modules/grunt/lib/util/task.js:251:24)
        at Task.<anonymous> (node_modules/grunt/lib/util/task.js:300:12)
        at node_modules/grunt/lib/util/task.js:227:11
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)

**node_modules/grunt/lib/grunt/task.js:260**:

```javascript
257    Object.defineProperty(this, 'filesSrc', {                                    
258      enumerable: true,                                                          
259      get: function() {                                                          
260        return grunt.util._(this.files).chain().pluck('src').flatten().uniq().value();
261      }.bind(this)                                                               
262    });
```

**Cause**:

lodash v4.0.0 removed `pluck` in favour of `map` (which can now take a string). On my system, `node_modules/grunt-legacy-util/node_modules` didn't exist (not sure why), but `node_modules/lodash` (v4.x) did. In the absence of a nested lodash, the top-level lodash was being used (cf. peer dependencies).

**Solution**

```shell
mv node_modules old.node_modules
npm install
```

If the error still occurs, update npm, do another fresh `npm install`, and ensure the following conditions are met:

* If the `filesSrc` getter uses `pluck`,  `node_modules/grunt-legacy-util/node_modules/lodash` must be < v4.0.0.
* If the `filesSrc` getter uses `map`, `node_modules/grunt-legacy-util/node_modules/lodash` must be >= v4.0.0.

**Comment by chocolateboy** [comment]
Just spotted another example of this where there's a discrepancy between a package in `node_modules` and the tarball for that module on NPM. Specifically, the `package.json` for a nested dependency (glob-stream) didn't match the `index.js` for that package (pumpify is `require`d in the `index.js` but not mentioned in the `package.json` even though it's in both in the tarball). This was occurring with npm v2.15.1 on node v0.10.48.

Reinstalling `node_modules` didn't help, but clearing the [NPM cache](https://docs.npmjs.com/cli/cache) and reinstalling did:

```
$ npm cache clear
$ rm -rf node_modules
$ npm install
```

**Comment by chocolateboy** [comment]
It might have something to do with this: https://github.com/npm/npm/issues/4042

**Comment by Ali7285** [comment]
_.chain(...).pluck is not a function
